### PR TITLE
Jan1622 Anomaly Report

### PR DESCRIPTION
**Pull request by jazan12**
BEP bus crash anomaly page draft provided here.

### CODE REVIEW

**Comment by richardjedgar** [comment]
Looks good to me (for whatever that's worth).

**Comment by jazan12** [comment]
> 

Really appreciate you taking a look Dick!

**Comment by Gregg140** [comment]
Under:

What is it?
-----------
........  ACIS will continue to perform observations, but the calibration will be unreliable.


Do you also want to point  out the other lost capabilities such as CC3x3?

Under:

How is this Anomaly Diagnosed?
------------------------------
DPA power and current (``1DPICACU``, ``1DPICBCU``)
will drop at the time of reset, on either or both sides.


Do you want to roughly specify the value to which they will drop?

Otherwise looks fine.

**Comment by cegrant** [comment]
> PMON will show that the software will has reset to v11, with the watchdogFlag set to 1. (Note that the warmbootFlag will likely be set to unity, which does not indicate that a warmboot occurred, but rather than a commanded boot would apply patches.) A fatalMessage packet written into telemetry by the active BEP reports the BEP CPU's BadVaddr register.

Here's a screenshot from the anomaly.  I think there needs to be more explicit explanation of what you see in PMON.

Screen Shot 2022-01-15 at 8 42 25 PM

If anomaly happens while not in comm, pmon will come up with a number of red items:
1STAT2ST, indicating a watchdog boot
A status message that FSW VERSION = 11
The SW HK packets will show VERSION = 1

If anomaly happens in comm, you will also see the initial FATAL ERROR message, which will be overwritten by the FSW VERSION = 11 message.  You will also see the time of boot.

The watchdog flag and warm boot flag are only in the bepStartup message, so they aren't really helpful in the text here.

You could then reference Peter's memo, "The contents of the fatalMessage and bepStartupMEssage are shown in <link to Peter's memo>.

**Comment by cegrant** [comment]
The CAP link is broken.  It should be:
https://occweb.cfa.harvard.edu/occweb/FOT/configuration/CAPs/1501-1600/CAP_1597_Restart%20ACIS/CAP_1597_Restart%20ACIS.pdf

**Comment by jazan12** [comment]
Thanks guys, your comments have been incorporated in the latest draft.  Except, Gregg, you asked "Do you want to roughly specify the value to which they will drop?"  I don't think we can as it should be different case-by-case.  (E.g., it's not like a WSPOW00000 or something where things would necessarily drop repeatably.)

**Comment by Gregg140** [comment]
> Thanks guys, your comments have been incorporated in the latest draft. Except, Gregg, you asked "Do you want to roughly specify the value to which they will drop?" I don't think we can as it should be different case-by-case. (E.g., it's not like a WSPOW00000 or something where things would necessarily drop repeatably.)

It would not hurt us to have a list for the number of boards active what the currents would be.

**Comment by jzuhone** [comment]
Hi @jazan12, 

This looks good to me--only thing I would potentially add is that you can also look at the current data real-time in MAUDE. But I don't want to hold this up any longer so I could add that detail later.

**Comment by cegrant** [comment]
I'm not sure what "the calibration will be unreliable" is supposed to mean.  (I meant to make this comment before but I think it got lost somewhere).  How about something like this:
ACIS will continue to perform observations but without the patches that provide various bug fixes, condition the overclocks, and the CC3x3 and event histogram observing modes.
 (And thanks for fixing all the acis->acisweb links!)

**Pull request merged**
