### PR TITLE
FEP Reset updates after last occurrence

### PR DESCRIPTION
**Pull request by jzuhone**
These are some changes to note the most recent instance of the FEP Reset anomaly. 

I have also reorganized the DPA-A/B shutdown pages a bit, no content changes here.

### CODE REVIEW

**Review by jazan12 — APPROVED** [review]
Looks good

**Comment by cegrant** [comment]
I note that the link for the ObsID 15232 memo doesn't show up here on GitHub?  It is on the released web page so I'm assuming that's just a weird GitHub thing.

For myself, I would like to add a sentence to #5 under diagnosis.  "They should find the time of the last event packets from the affected FEPs and the time that the FEP resets were reported in software housekeeping."  Add a sentence "If the anomaly occurs during bias creation, there will not be any event packets and there may not be any FEPREC_RESET messages in software housekeeping."

Otherwise, this looks good to me.

**Comment by cegrant** [comment]
"event packets from the affected FEPs"

**Review by cegrant — APPROVED** [review]
OK by me.

**Review by jazan12 — APPROVED** [review]
Good by me!

**Review by Gregg140 — APPROVED** [review]
Looks fine to me
Gregg

**Comment by pplucinsky** [comment]
Looks good to me.

**Pull request merged**
