### PR TITLE
Trickle-bias T-plane doc updates

### PR DESCRIPTION
**Pull request by jzuhone**
Royce's updates to this page. A rendered version of these changes appears at:

http://cxc.cfa.harvard.edu/acis/tmp/tbias_tplane/trickle_bias_tplane.html

### CODE REVIEW

**Review by richardjedgar — COMMENTED** [review]
In the diagnosis section, we refer to "FOT Data Processing". I think we mean CXC DSOPS (i.e Joy's group).

**Comment by richardjedgar** [comment]
This looks good to me.

**Comment by jzuhone** [comment]
This looks good to me also.

**Review by richardjedgar — APPROVED** [review]

**Review by Gregg140 — APPROVED** [review]
The changes and clarifications look good to me.

**Pull request merged**
