### PR TITLE
Made edits collected during Teram Tagup Review

### PR DESCRIPTION
**Pull request by Gregg140**
Pull request to allow checking the edits I made

### CODE REVIEW

**Review by richardjedgar — CHANGES_REQUESTED** [review]
Really minor typo: In line 62: change 'thatn' to 'that'. Otherwise this looks good.

**Comment by Gregg140** [comment]
Thanks for the catch...actually it needed to be changed to "than"

G

**Comment by jzuhone** [comment]
So after talking with @Gregg140, I think he should make the edits not on this branch but off the top of the `fep_reset_may2017` branch, which includes the changes that he sent to me a little while ago (including the fix to the typo @richardjedgar mentioned above)

Sorry, I should have been more clear about this before. So long as that makes sense, @Gregg140, can you close this, add your changes onto that branch, and then make a new PR from that branch?

**Comment by jzuhone** [comment]
Closing because @Gregg140 submitted a new one.

**Pull request closed without merging**
